### ISSUE TITLE
Set trust on private key import

### ISSUE THREAD

**Issue by pryrt** [crazy-max/ghaction-import-gpg#118]
### Behaviour

When I use this action to set up gpg, it imports the private key just fine, but it doesn't set any trust.

For the deployment that I am trying to set up, I want to be able to both sign and verify with the key

#### Steps to reproduce this issue

1. use your example setup
2. gpg sign a file from my repo
3. `gpg --verify` that signature

#### Actual behaviour

```
gpg: Signature made Wed Nov 24 19:03:33 2021 UTC
gpg:                using RSA key xxxxx
gpg: Good signature from "Peter's Signing Key" [unknown]
gpg:                 aka "Peter <xxx@xxx.org>" [unknown]
gpg:                 aka "Peter <yyy@yyy.com>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
```

#### Expected behaviour

It should trust my own key, something like:
```
gpg: Signature made Wed Nov 24 19:35:18 2021 UTC
gpg:                using RSA key DEADBEEF
gpg: Good signature from "Peter's Signing Key" [ultimate]
gpg:                 aka "Peter <xxx@xxx.org>" [ultimate]
gpg:                 aka "Peter <yyy@yyy.com>" [ultimate]
```

### Configuration
```yml
# This is a basic workflow to help you get started with Actions

name: perl-deploy-gpg

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    tags: '*'
    branches: '*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Set up GPG per https://stackoverflow.com/a/66457517/5508606 ; updated by most recent example in action repo
      - name: Import GPG Key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v4
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}

      # official example
      - name: GPG user IDs
        run: |
          echo "fingerprint: ${{ steps.import_gpg.outputs.fingerprint }}"
          echo "keyid:       ${{ steps.import_gpg.outputs.keyid }}"
          echo "name:        ${{ steps.import_gpg.outputs.name }}"
          echo "email:       ${{ steps.import_gpg.outputs.email }}"

      # my experiments
      - name: My experiments
        run: |
          echo detach sign
          gpg --local-user 0xDEADBEEF --detach-sign --armor Makefile.PL
          
          echo verify
          gpg --verify Makefile.PL.asc Makefile.PL
```

### Workaround

if I add the following step after the `Import GPG Key` step, then I get the "expected behavior"
```yml
      # trust myself
      - name: Update Trust = Trust myself
        id: trust_myself
        run: |
          gpg --no-tty --command-fd 0 --edit-key 0xDEADBEEF << EOTRUST
          trust
          5
          y
          quit
          EOTRUST
```

It would be nice if your action set the trust by default, or at least allowed a `with:` parameter to set the `trustlevel` -- accepting the values of 1-5
```
  1 = I don't know or won't say
  2 = I do NOT trust
  3 = I trust marginally
  4 = I trust fully
  5 = I trust ultimately
```

**Comment by crazy-max** [comment]
A new input sgtm

**Comment by crazy-max** [comment]
@pryrt Also if you want a oneliner, you can just do: https://github.com/docker/docker-credential-helpers/blob/ac5992b5f4756fc0398a7d0c93c609e624368bde/.github/workflows/build.yml#L94

```yaml
      - name: Update Trust = Trust myself
        run: |
          echo -e "trust\n5\ny" | gpg --batch --no-tty --command-fd 0 --edit-key 0xDEADBEEF
```
