### ISSUE TITLE
Transient ERR 67108891 Not found <GPG Agent>

### ISSUE THREAD

**Issue by henrygriffiths** [crazy-max/ghaction-import-gpg#119]
### Behavior

> When running the action multiple times in an actions matrix (using a self-hosted runner), the gpg import occasionally fails with ERR 67108891 Not found <GPG Agent>

#### Steps to reproduce this issue

1. Use working crazy-max/ghaction-import-gpg@v4 setup
2. Implement in GitHub Actions Matrix
3. Run action many times on self-hosted runner

#### Expected behavior

> The GPG key is successfully imported and the action completes successfully

#### Actual behavior

> 1 in every 15-20 times, the action fails with `ERR 67108891 Not found <GPG Agent>`
> ![image](https://user-images.githubusercontent.com/42880130/148701956-171dfad7-89d7-4b1d-8a0a-6ece84929826.png)
> If the action is re-run, sometimes the same error occurs (sometimes on the same matrix job, sometimes a different one), and sometimes the job completes successfully.

### Configuration

* Repository URL (if public): N/A
* Build URL (if public): N/A

```
    - name: Import GPG key
      uses: crazy-max/ghaction-import-gpg@v4
      with:
        gpg_private_key: ${{ secrets.BOT_GPG_PRIVATE_KEY }}
        passphrase: ${{ secrets.BOT_GPG_PRIVATE_KEY_PASS }}
        git_user_signingkey: true
        git_commit_gpgsign: true
```

### Logs

> [actionlog.txt](https://github.com/crazy-max/ghaction-import-gpg/files/7836021/actionlog.txt)
