### ISSUE TITLE
Error: Misformed armored text

### ISSUE THREAD

**Issue by patsevanton** [crazy-max/ghaction-import-gpg#122]
Hello! Thanks for github action crazy-max/ghaction-import-gpg

1) gpg --export-secret-keys 9282DE1880469BB2EFE0CA4344850777D482CAC8 | base64 > private.key
2) Create github secret GPG_SIGNING_KEY from private.key and GPG_PASSPHRASE

Github action
```
      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v4
        with:
          gpg_private_key: ${{ secrets.GPG_SIGNING_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
```

Error:
```
Run crazy-max/ghaction-import-gpg@v4
  with:
    gpg_private_key: ***
    passphrase: ***
    git_config_global: false
    git_user_signingkey: false
    git_commit_gpgsign: false
    git_tag_gpgsign: false
    git_push_gpgsign: if-asked
    workdir: .
GnuPG info
  Version    : 2.2.[1] (libgcrypt 1.8.5)
  Libdir     : /usr/lib/x86_6[4]-linux-gnu/gnupg
  Libexecdir : /usr/lib/gnupg
  Datadir    : /usr/share/gnupg
  Homedir    : /home/runner/.gnupg
Error: Misformed armored text
```

Code https://github.com/Drill4J/logger-api/blob/master/.github/workflows/publish.yml
Log https://github.com/Drill4J/logger-api/runs/5184058495?check_suite_focus=true
