### ISSUE TITLE
67108933 Not implemented <GPG Agent>

### ISSUE THREAD

**Issue by marcofranssen** [crazy-max/ghaction-import-gpg#146]
#### Steps to reproduce this issue

1. Create a key with subkeys. 
2. Add a subkey for signing using ecdsa.
3. Add a subkey for signing using RSA.
4. export the key using ascii armor. `gpg --armor --export-secret-keys KEYID | pbcopy`
5. 

In this workflow I am selecting the RSA subkey for signing.

#### Expected behaviour

The key should successfully load into the gpg-agent.

#### Actual behaviour

Running this workflow fails with following log

```shell
Configuring GnuPG agent
::group::Getting keygrip for fingerprint
Getting keygrip for fingerprint
Error: ERR 67108933 Not implemented <GPG Agent>
```

### Configuration

* Repository URL (if public): https://github.com/marcofranssen/terraform-provider-curl
* Build URL (if public): https://github.com/marcofranssen/terraform-provider-curl/runs/7641373924?check_suite_focus=true

```yaml
name: release
on:
  push:

jobs:
  release-provider:
    runs-on: ubuntu-22.04

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v3.2.1
        with:
          go-version-file: 'go.mod'
          check-latest: true
          cache: true

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v5.0.0
        id: gpg
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          fingerprint: EA0A37E819AFBAE6

    …
    …
    …
```

### Logs

See attached build URL.
