### ISSUE TITLE
Unable to export GPG key

### ISSUE THREAD

**Issue by jdstone** [crazy-max/ghaction-import-gpg#161]
#### Steps to reproduce this issue

1. Set your GitHub secrets:
    1. `${{ secrets.GPG_PRIVATE_KEY }}`
    2. `${{ secrets.GPG_PASSPHRASE }}`
    3. `${{ secrets.GPG_KEY_ID }}`
2. Configure a GitHub action like so
```yaml
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          fingerprint: ${{ secrets.GPG_KEY_ID }}

      - name: Export GPG key to legacy format
        run: gpg --export-secret-keys > ~/.gnupg/pubring.gpg
````
3. Run the action

#### Expected behaviour

GPG should export the specified GPG key into `~/.gnupg/pubring.gpg`

#### Actual behaviour

The import step completes successfully, but exporting the key does not.  Below is what is shown:

```
  Run gpg --export-secret-keys > ~/.gnupg/pubring.gpg
  gpg --export-secret-keys > ~/.gnupg/pubring.gpg
  shell: /usr/bin/bash -e {0}
gpg: key 3542E92F08CF2673973F54E25347ACDAC05744B8: error receiving key from agent: Inappropriate ioctl for device - skipped
gpg: 672E6CBF977A40F508F88F4CBBE8211E927B068C: error receiving key from agent: Inappropriate ioctl for device - skipped
gpg: WARNING: nothing exported
Error: Process completed with exit code 2.
```

Note: I know it shows I used `crazy-max/ghaction-import-gpg@v5`, but before that version, I tried the latest `v5.2.0`.
<img width="679" alt="gpg_screenshot" src="https://user-images.githubusercontent.com/817664/227752560-4f5337f2-82d1-44ab-a5b4-92c46162675b.png">

Haha, I guess it didn't make a difference to block out that information. 😛

### Configuration

* Repository URL (if public): https://github.com/jdstone/helm-charts
* Build URL (if public): https://github.com/jdstone/helm-charts/actions/runs/4522300214/jobs/7964665430

```yml
name: Release Charts

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.8.1

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          fingerprint: ${{ secrets.GPG_KEY_ID }}

      - name: Export GPG key to legacy format
        run: gpg --export-secret-keys > ~/.gnupg/pubring.gpg

      - name: Add dependency chart repos
        run: |
          helm repo add jdstone https://charts.jdstone.dev

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.5.0
        with:
          charts_dir: charts
          config: cr.yaml
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

```

### Logs

[logs_47.zip](https://github.com/crazy-max/ghaction-import-gpg/files/11070648/logs_47.zip)
