### ISSUE TITLE
Keygrip empty

### ISSUE THREAD

**Issue by mkrakowitzer** [crazy-max/ghaction-import-gpg#162]
### Behaviour
Action runs and fails with
```
17:16:34.041447 git.c:439               trace: built-in: git commit -m '[NO-JIRA] Update CODEOWNERS file'
17:16:34.048912 run-command.c:655       trace: run_command: gpg --status-fd=2 -bsau EF1A6F3A62520D9C
error: gpg failed to sign the data:
gpg: skipped "EF1A6F3A62520D9C": No secret key
[GNUPG:] INV_SGNR 9 EF1A6F3A62520D9C
[GNUPG:] FAILURE sign [17](https://github.com/XXXXXXXXXXX#step:9:18)
gpg: signing failed: No secret key
```

When reviewing the logs the keygrip is empty

```
Run crazy-max/ghaction-import-gpg@v5
  with:
    gpg_private_key: ***
    passphrase: ***
    git_config_global: true
    git_user_signingkey: true
    git_commit_gpgsign: true
    git_tag_gpgsign: false
    git_push_gpgsign: if-asked
    workdir: .
GnuPG info
  Version    : [2](https://#step:7:2).2.27 (libgcrypt 1.9.4)
  Libdir     : /usr/lib/x86_64-linux-gnu/gnupg
  Libexecdir : /usr/lib/gnupg
  Datadir    : /usr/share/gnupg
  Homedir    : /home/runner/.gnupg
GPG private key info
  Fingerprint  : CAD7ADA00BA95F757[3](https://#step:7:3)A6B291EF1A6F3A62[5](#step:7:5)20D9C
  KeyID        : EF1A[6](https://#step:7:6)F3A62520D9C
  Name         : camelotMachineUser
  Email        : XXXX@XXXXXXX.com
  CreationTime : Tue Apr 18 2023 1[7](#step:7:7):07:23 GMT+0000 (Coordinated Universal Time)
Fingerprint to use
  CAD7ADA00BA[9](https://#step:7:9)5F7573A6B291EF1A6F3A625[20](https://#step:7:22)D9C
Importing GPG private key
  gpg: directory '/home/runner/.gnupg' created
  gpg: keybox '/home/runner/.gnupg/pubring.kbx' created
  gpg: /home/runner/.gnupg/trustdb.gpg: trustdb created
  gpg: key EF1A6F3A62520D9C: public key "camelotMachineUser (BOT account for camelot builds) <XXXX@XXXX.com>" imported
  gpg: Total number processed: 1
  gpg:               imported: 1
Configuring GnuPG agent
Getting keygrips
Setting outputs
  fingerprint=CAD7ADA00BA95F7573A6B291EF1A6F3A62520D9C
  keyid=EF1A6F3A6[25](XXXXXXXXX9#step:7:29)20D9C
  name=XXXXXXXXXX
  email=XXXXXXX@XXXXXXXX.com
Setting GPG signing keyID for this Git repository
Configuring Git committer (XXXXXX <XXXXXX@XXXXXXX.com>)
Sign all commits automatically
Sign all pushes automatically
```
#### Steps to reproduce this issue

1. Created a new GPG key for a bot account, added to the account + created the required github secret for the key + passphrase
2. Create the github action
3. run workflow without the error

#### Expected behaviour

> Tell me what should happen
gpg -K should probably list keys but it doesn't
Should be able to sign commits

#### Actual behaviour
Fails with an error
```
17:16:34.041447 git.c:439               trace: built-in: git commit -m '[NO-JIRA] Update CODEOWNERS file'
17:16:34.048912 run-command.c:655       trace: run_command: gpg --status-fd=2 -bsau EF1A6F3A62520D9C
error: gpg failed to sign the data:
gpg: skipped "EF1A6F3A62520D9C": No secret key
[GNUPG:] INV_SGNR 9 EF1A6F3A62520D9C
[GNUPG:] FAILURE sign [17](https://github.com/XXXXXXXXXXX#step:9:18)
gpg: signing failed: No secret key
```
### Configuration

* Repository URL (if public): private
* Build URL (if public): private

```yml
      - name: Import bot's GPG key for signing commits
        id: import-gpg
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.MACHINEUSER_GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.MACHINEUSER_GPG_PASSPHRASE }}
          git_config_global: true
          git_user_signingkey: true
          git_commit_gpgsign: true
      - name: List keys
        run: gpg -K
      - name: Commit changes
        if: steps.verify-changed-files.outputs.files_changed == 'true'
        run: |
          git add .github/CODEOWNERS
          git add README.md
          export GIT_TRACE=1
          git commit -m "[NO-JIRA] Update CODEOWNERS file"
```

### Logs

> Download the [log file of your build](https://docs.github.com/en/actions/managing-workflow-runs/using-workflow-run-logs#downloading-logs)
> and [attach it](https://docs.github.com/en/github/managing-your-work-on-github/file-attachments-on-issues-and-pull-requests) to this issue.
