### ISSUE TITLE
GPG opens TTY pinentry even though passphrase was configured

### ISSUE THREAD

**Issue by oSumAtrIX** [crazy-max/ghaction-import-gpg#206]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/crazy-max/ghaction-import-gpg/blob/master/.github/SUPPORT.md)

### I've found a bug and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

Failed run: https://github.com/ReVanced/revanced-integrations/actions/runs/9941090414/job/27459330993#step:9:235
Usage of the action: https://github.com/ReVanced/revanced-integrations/blob/dev/.github/workflows/release.yml#L43-L48
This step will run GPG (with --no-tty): https://github.com/ReVanced/revanced-integrations/blob/dev/.github/workflows/release.yml#L53:

![image](https://github.com/user-attachments/assets/78bbe055-e1b4-49e8-bc38-b89993884216)

The above null checks should all be false because I do not set them:  https://github.com/ReVanced/revanced-integrations/blob/dev/app/build.gradle.kts#L68-L71

Note this issue only started to occur when I specified the fingerprint of a subkey. Previously I was doing that wrong. (I used `env.` instead of `var.` when my fingerprint was a repo variable). Before correcting it, the master key was being imported and the workflow run worked fine: https://github.com/ReVanced/revanced-integrations/actions/runs/9912018034/job/27385936781

### Expected behaviour

No pin entry is being opened/The files are signed with the subkey.

### Actual behaviour

It seems like pinentry is being opened which causes the error: `gpg: signing failed: Inappropriate ioctl for device`

### Steps to reproduce

1. Clone https://github.com/ReVanced/revanced-integrations/tree/dev
2. Setup the env/repo variables
3. Dispatch the release workflow manually

### Repository URL

https://github.com/ReVanced/revanced-integrations

### Workflow run URL

https://github.com/ReVanced/revanced-integrations/actions/runs/9941090414/job/27459330993

### YAML workflow

```yaml
name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Make sure the release step uses its own credentials:
          # https://github.com/cycjimmy/semantic-release-action#private-packages
          persist-credentials: false
          fetch-depth: 0

      - name: Cache Gradle
        uses: burrunan/gradle-cache-action@v1

      - name: Setup Java
        run: echo "JAVA_HOME=$JAVA_HOME_17_X64" >> $GITHUB_ENV

      - name: Build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew build clean

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          fingerprint: ${{ vars.GPG_FINGERPRINT }}

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.REPOSITORY_PUSH_ACCESS }}
        run: npm exec semantic-release
```

### Workflow logs

https://github.com/ReVanced/revanced-integrations/suites/26016689801/logs?attempt=1

### Additional info

Interestingly, the same approach (Importing the subkey and signing with it) works in this run: https://github.com/ReVanced/revanced-api/actions/runs/9920663564/job/27407772404#step:7:45
