### ISSUE TITLE
Unable to read Private Keys

### ISSUE THREAD

**Issue by dcaponi** [crazy-max/ghaction-import-gpg#47]
### Behaviour
I'm setting this up in a github action as part of HashiCorp's recommended workflow 
#### Steps to reproduce this issue

1. Create a set of public and private GPG keys
    I created them with `gpg --gen-key` selecting option 4 RSA (sign only) answering the prompts (2048 bit length) and setting the key to never expire
2. Add the following node to a github action
```
- name: Import GPG key
        id: import_gpg
        uses: paultyng/ghaction-import-gpg@v2.1.0
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          PASSPHRASE: ${{ secrets.PASSPHRASE }}
```
3. add the secrets `GPG_PRIVATE_KEY` and `PASSPHRASE` to the repo where `GPG_PRIVATE_KEY` came from `gpg --armor --export-secret-key <user_email> | pbcopy` which gives an output that looks normal
```
-----BEGIN PGP PRIVATE KEY BLOCK-----

<stuff>
-----END PGP PRIVATE KEY BLOCK-----

```
4. run the github action

#### Expected behaviour

> It should import my GPG key so it can be used in goreleaser to sign my binaries.

#### Actual behaviour

> Run paultyng/ghaction-import-gpg@v2.1.0
> 📣 GnuPG info
> Version    : 2.2.4 (libgcrypt 1.8.1)
> Libdir     : /usr/lib/x86_64-linux-gnu/gnupg
> Libexecdir : /usr/lib/gnupg
> Datadir    : /usr/share/gnupg
> Homedir    : /home/runner/.gnupg
> 🔮 Checking GPG private key
> ##[error]Could not find valid encryption key packet in key 4198c6cc29feabf7

### Configuration

* Repository URL (if public): https://github.com/onelogin/terraform-provider-onelogin
* Build URL (if public): https://github.com/onelogin/terraform-provider-onelogin/runs/908376161

```yml
on:
  push:
    tags:
    - '*'
name: Release
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Unshallow
        run: git fetch --prune --unshallow
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14
      - name: Import GPG key
        id: import_gpg
        uses: paultyng/ghaction-import-gpg@v2.1.0
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          PASSPHRASE: ${{ secrets.PASSPHRASE }}
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GPG_FINGERPRINT: ${{ steps.import_gpg.outputs.fingerprint }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
obtained from https://github.com/hashicorp/terraform-provider-scaffolding/blob/master/.github/workflows/release.yml

### Logs
[logs_174.zip](https://github.com/crazy-max/ghaction-import-gpg/files/4974376/logs_174.zip)
