### ISSUE TITLE
Wrong instructions for exporting with Arch Linux

### ISSUE THREAD

**Issue by ranisalt** [crazy-max/ghaction-import-gpg#59]
#### Steps to reproduce this issue

1. Export a key with `gpg --armor --export-secret-key joe@foo.bar | sed -z 's;\n;;g' | xclip -selection clipboard -i` on Arch Linux

#### Expected behaviour

Key should be imported to the keyring

#### Actual behaviour

Outputs "malformed key" when importing the key using the action.

Removing `sed -z 's;\n;;g'` works.

### Configuration

```yml
  - uses: crazy-max/ghaction-import-gpg@v3
      id: gpg
      with:
        gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
```

### Logs

N/A
