### ISSUE TITLE
Error Checking GPG private key

### ISSUE THREAD

**Issue by jbrunetext** [crazy-max/ghaction-import-gpg#71]
#### Steps to reproduce this issue

1.Export the Prvate Key :
 gpg --armor --export-secret-key F1840E7D69CDF54D66EFAAA762B9XXXXXXXXXX -w0
2.Create GPG_PRIVATE_KEY  AND PASSPHRASE 
3.git tag -f v0.0.1

#### Expected behaviour

signed artefact with gpg

#### Actual behaviour

> my artefact should be signed but i faced a issue add step Import GPG key 
i don't know why i cannot import the key
 Checking GPG private key
Error: Could not find valid encryption key packet in key 62xxxxxxxx

### Configuration

* Repository URL (if public): 
* Build URL (if public): 

```yml
name: release
on:
  push:
    tags:
      - 'v*'
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Unshallow
        run: git fetch --prune --unshallow
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14
      -
        name: Import GPG key
        id: import_gpg
        uses: paultyng/ghaction-import-gpg@v2.1.0
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          PASSPHRASE: ${{ secrets.PASSPHRASE }}
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GPG_FINGERPRINT: ${{ steps.import_gpg.outputs.fingerprint }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

### Logs

> Download the [log file of your build](https://help.github.com/en/actions/configuring-and-managing-workflows/managing-a-workflow-run#downloading-logs) and [attach it](https://help.github.com/en/github/managing-your-work-on-github/file-attachments-on-issues-and-pull-requests) to this issue.
