### ISSUE TITLE
Sign plain files

### ISSUE THREAD

**Issue by szepeviktor** [crazy-max/ghaction-import-gpg#73]
#### Steps to reproduce this issue

```yaml
      - name: "Import GPG key"
        id: "import_gpg"
        uses: "crazy-max/ghaction-import-gpg@v3"
        with:
          gpg-private-key: "${{ secrets.GPG_PRIVATE_KEY }}"

      - name: "Sign PHAR file"
        run: |
          export GPG_TTY="$(tty)"
          gpg --detach-sign --output build/bin/rector.phar.asc build/bin/rector.phar
```

#### Expected behaviour

I'd like to sign a PHAR file.

#### Actual behaviour

> gpg: signing failed: No such file or directory

### Configuration

https://github.com/szepeviktor/rector-phar/runs/1652311216?check_suite_focus=true
