### ISSUE TITLE
Getting error `gpg: error reading key: No secret key`

### ISSUE THREAD

**Issue by ppiyush13** [crazy-max/ghaction-import-gpg#80]
#### Steps to reproduce this issue

1. Create gpg keys using `gpg --gen-key`
1. Get private key using `gpg --armor --export <sec_key>`
1. Create github repo secrets GPG_PRIVATE_KEY for passphrase and GPG_PASSPHRASE with step 2 private key
1. Try running ghaction-import-gpg as below

#### Expected behaviour

> It must complete execution without errors

#### Actual behaviour

> Error: gpg: error reading key: No secret key

### Configuration

```yml
- name: Import GPG key
  uses: crazy-max/ghaction-import-gpg@v3.1.0
  with:
    gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
    passphrase: ${{ secrets.GPG_PASSPHRASE }}
    git-user-signingkey: true
    git-commit-gpgsign: true
    git-tag-gpgsign: true
  env:
    debug: true
```

### Logs

![image](https://user-images.githubusercontent.com/3319815/113324374-a4f47a00-9334-11eb-90e2-006e308c6022.png)
